### ISSUE TITLE
[features] guide how to hack

### ISSUE THREAD

**Issue by truonghoangnguyen** [ptgamr/upnext#17]
hi 

very nice if soundcloudify have guide how to develop / test / some basic guide to setting up environment

thanks.

**Comment by ptgamr** [comment]
Oh thanks for your heads up.

I will find some time adding it to the README file

**Comment by ptgamr** [comment]
Actually it is very simple:

1. git clone the project
2. `npm install`
3. `bower install`
4. Enable developer mode in Chrome, import /app folder and there you go

If you wanna make a built, run `grunt build`
