### ISSUE TITLE
Support OS X media playback keys

### ISSUE THREAD

**Issue by maxyankov** [ptgamr/upnext#26]
OS X has a centralised mechanism for media control keys, play/pause, next and previous. It would be nice if this plugin would support these keys.

**Comment by ptgamr** [comment]
Should be in the next version

**Comment by ptgamr** [comment]
Supported since 1.2.7

https://chrome.google.com/webstore/detail/upnext-music-player/dgkfcdlmdppfhbfmooinbcejdaplobpk
