### ISSUE TITLE
Access to Liked videos playlist from YouTube?

### ISSUE THREAD

**Issue by orschiro** [ptgamr/upnext#34]
Dear @ptgamr, 

What a great extension. Thank you very much!

I have one question. 

Is it possible to access my Liked videos playlist from YouTube through upnext?

Warmly,

Robert

**Comment by ptgamr** [comment]
Hey @orschiro , you're able to import Youtube Playlist to listen on UpNext. Your Liked videos is also a playlist, just grab its URL and use import functionality and you're good to go :)

**Comment by ptgamr** [comment]
Let me know if you have any problem with that.

**Comment by orschiro** [comment]
Dear @ptgamr,

That's great! I had to make my `Liked Videos` public first but then I was able to import the list.

Will upnext automatically update the playlist if I remove or add videos to my `Liked Videos` on YouTube?

Robert

**Comment by ptgamr** [comment]
It doesn't at the moment , but yeah, would be great if UpNext could support this functionality. I would not have enough time to do this, so any contribution are welcome :)
