### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by JIVS** [ptgamr/upnext#48]
Anyone else having this problem? did YT finally kill it?

**Comment by Hakalon** [comment]
me too, the music from SoundCloud have the same problem, so I don't think it's related to YT.

**Comment by Bernkastel07th** [comment]
me too.
It was useless even to reboot chrome, pc...

### PC environment
- macOS(El capitan)
- GoogleChrome(latest)

**Comment by benyemna** [comment]
i have the same issue.
i looked into the background console and i got this: 

`background.js:3 open db ...
background.js:3 open db DONE
background.js:4 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('chrome-extension://onmajobkcaongppiegaopmilaggopjlc').`

- google chrome v56.0.2924.87
- Win7

**Comment by ptgamr** [comment]
Alright guys... hold on. I've been able to reproduced this. Will investigate it very soon

**Comment by ptgamr** [comment]
While I'm working on the fix... Please use the web version instead:

http://soundcloudify.github.io/#/search

**Comment by JIVS** [comment]
Hey have you considered making a desktop app version with electron?

**Comment by ptgamr** [comment]
Nope... I haven't got time to think about that yet. It will be requiring much time which I don't really have at the moment

**Comment by ptgamr** [comment]
FYI, Chrome 56 Upgrade caused the extension to not working anymore. It still works fine on Chrome 55 though.

The reason might be that the new Chrome don't allow extension to load Iframe anymore in its background page. But haven't found the evidence yet.

I'm trying to think of a solution, but this might need a dramatic change in the extension code.

**Comment by ICasula** [comment]
Thanks for the info! I've been able to rollback chrome to version 55 and now it works again. Meanwhile, I've also disabled Chrome's autoupdate, so, everything is fine now.

If anybody wants a link to the working version for 64bit, here's the link: https://userscloud.com/f15jwj0b4ezu

And here's the procedure I used to replace version 56 with version 55 (do NOT install):  https://productforums.google.com/forum/#!topic/chrome/UFSYuIr1-80

**Comment by ICasula** [comment]
BTW, has anybody figured out how to disable the warning message I get everytime I open Chrome telling me that I should disable extensions in developer mode?

**Comment by coffenbacher** [comment]
The web based version is awesome, I didn't even know it existed. I prefer it, to be honest, because it avoids some Chrome browser bugs I have with extensions and multiple monitors. Thanks for linking!

**Comment by RubenPHP** [comment]
The problem was solved on Chrome v57. You can see updated info about this issue [here](https://bugs.chromium.org/p/chromium/issues/detail?id=698545)

I've Chrome v57 installed and the extension is working OK (on v56 it doesn't worked)

**Comment by ptgamr** [comment]
Wow thanks @RubenPHP for your finding... I was stuck with the error for days, couldn't think of a solution. The bug in chromium doesn't look like the bugs we are getting but glad that it fix our issue ;)

**Comment by benyemna** [comment]
+1 it's working again after the last update of chrome (Version 57.0.2987.98)

**Comment by andrizmitnick** [comment]
is there any solution regarding this?
i'm on latest chrome 72
